Added circleci config validation in precommit hook
Also included cstddef in score_manager.h to get rid of compilation
error. Has been already done in another branch but not in master, so I
had to add it here to make the code compile

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,4 +1,8 @@
 #!/bin/bash
+
+# Needed by circleci local build tool
+exec < /dev/tty
+
 echo "##### Running pre-commit hook #####"
 root="$(pwd)"
 
@@ -7,3 +11,12 @@ bash "${root}/.githooks/clangformat.sh"
 
 # Run cmake-format on cmake lists files
 bash "${root}/.githooks/cmakeformat.sh"
+
+# Referred:  https://circleci.com/blog/circleci-hacks-validate-circleci-config-on-every-commit-with-a-git-hook/
+# Validates circleci config file
+if ! msg=$(circleci config validate -c .circleci/config.yml); then
+	echo "Failed circleci validation"
+	exit 1
+else
+	echo $msg
+fi
